// AUTO-GENERATED by scripts/gen-companion-config.js from package.json (publisher: "replace-with-your-publisher-id", name: "codeforces-inline").
// Do not edit by hand — re-run "npm run gen:companion-config" instead.
var CF_DEEPLINK = {
    uriPrefix: 'vscode://replace-with-your-publisher-id.codeforces-inline/openProblem',
    marketplaceUrl: 'https://marketplace.visualstudio.com/items?itemName=replace-with-your-publisher-id.codeforces-inline'
};
